### ISSUE TITLE
Falta de manejo de excepciones en el boton Acciones y logica de regaño

### ISSUE THREAD

**Issue by Wallens1** [kealmahe2003/MiniproyectoPOE#19]
Se debe implementar el manejo de excepciones para los posibles errores al momento de ejecutar alguna accion del botón, pues este no tiene en cuenta el poner una letra como id o una id inexistente, además, por ejemplo no toma en cuenta si un Teniente tiene ya sus cualidades escogidas

Aquí un ejemplo al no poner nada en la ID

![image](https://github.com/user-attachments/assets/0567005e-1412-4c5c-85a3-1d30b660cba5)

Otro ejemplo al no añadir la cualidad del Capitán de soldados bajo su mando pues por defecto se le pone "No tiene" y este no es un entero dando un error:

![image](https://github.com/user-attachments/assets/3b9514dd-78a8-415a-ae1d-d2bc4414e7c6)

Por la parte de la lógica de regaño en la clase soldado se implemento el meto regaño y se añadió la cualidad nivelRango y la lógica de restar al momento de ser llamado el método, por lo que queda faltando poder regañar a un soldado desde un rango superior y restarle a su nivel de rango que por defecto se le puso 5 (no se puede cambiar actualmente) para que al momento de llegar a 0 este sea eliminado de la lista

**Comment by kealmahe2003** [comment]
Ya se implemento la funcionalidad de los regaños.
Por favor, es importante que se compruebe a fondo su correcto funcionamiento

Tambien se añadió manejo de excepciones a cierta parte del codigo pero faltaria agregarselo al completo
